version: 2

before:
  hooks:
    - go mod tidy

builds:
  - main: .
    id: cli
    binary: fyve
    ldflags: -s -w
    flags:
      - -trimpath
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - formats: [ tar.gz ]
    name_template: "fyve-cli_{{ .Os }}-{{ .Arch }}"
    files:
      - README.md

checksum:
  name_template: "checksums.txt"