version: 2

before:
  hooks:
    - go mod tidy

builds:
  - main: .
    id: cli
    binary: fyve
    ldflags: -s -w
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - format: binary