version: 2

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/fyve
    id: fyve
    binary: fyve
    ldflags: -s -w
    flags:
      - -trimpath
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

kos:
  - id: ghcr
    repositories:
      - ghcr.io/fyve-labs/fyve-cli
    bare: true
    base_image: gcr.io/distroless/static-debian12
    build: fyve
    main: ./cmd/fyve
    env:
      - CGO_ENABLED=0
    platforms:
      - linux/amd64
    tags:
      - "{{ .Tag }}"
      - "{{ if not .Prerelease }}latest{{ end }}"
      - "sha-{{ .ShortCommit }}"

archives:
  - formats: [ tar.gz ]
    name_template: "fyve-cli_{{ .Os }}-{{ .Arch }}"
    files:
      - README.md

checksum:
  name_template: "checksums.txt"