name: CI

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  auto-exchange-token-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.25
      - uses: Fyve-Labs/actions/configure-aws-credentials@main
      - uses: Fyve-Labs/actions/tailscale@main
      - name: BuildAndTest
        run: |
          go mod download
          go build -o fyve github.com/fyve-labs/fyve-cli/cmd/fyve
          ./fyve list
        env:
          FYVE_DEBUG: true