name: CI

on:
  push:
    branches:
      - main

permissions:
  id-token: write

jobs:
  exchange-token:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.24
      - name: Tailscale
        uses: tailscale/github-action@v3
        with:
          authkey: ${{ secrets.TAILSCALE_AUTHKEY }}
          version: latest
      - name: BuildAndRun
        run: |
          go mod download
          go build -o fyve github.com/fyve-labs/fyve-cli/cmd/fyve
          ./fyve list